### ISSUE TITLE
Undefined offsetlardan xalos bo'lish

### ISSUE THREAD

**Issue by SamixGroup** [terowoc/Telegram-Bot-Combot#1]
Update obyektining barcha xossalarini tekshirmasdan olmaslik
misol:
$text = $update["message"]["text"]  - 🚫
if(isset($update['message']) and isset($update['message']["text"]){
 $text = isset$update['message']["text"];
...}

**Comment by terowoc** [comment]
raxmat

**Comment by SamixGroup** [comment]
keyingi proyektlarda xal qilindi degan umidda yopildi
